- name: Install and mount NFS client on Ubuntu
  hosts: db
  become: yes
  tasks:
    # 1. NFS 클라이언트 패키지 설치
    - name: Install NFS client package
      apt:
        name: nfs-common
        state: present

    # 2. 마운트 지점 생성
    - name: Create mount directory
      file:
        path: /dir1
        state: directory
        mode: '0777'

    # 3. NFS 공유 마운트 (fstab 등록 X, 일회성)
    - name: Mount NFS share temporarily
      mount:
        src: 192.168.20.1:/sales
        path: /dir1
        fstype: nfs
        opts: rw,sync
        state: mounted

    # (선택) 4. 부팅 시 자동 마운트(fstab 등록)
    - name: Configure NFS mount persistent
      mount:
        src: 192.168.20.1:/sales
        path: /dir1
        fstype: nfs
        opts: rw,sync
        state: present
