- name: Install and configure Samba server on Ubuntu
  hosts: u22b
  become: yes  # 관리자 권한으로 실행
  vars_prompt:
    - name: "samba_user_password"
      prompt: "Please enter the password for the Samba user"
      private: yes  # 비밀번호를 숨김 처리
  tasks:
    # 1. apt 패키지 목록 갱신
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  # 1시간 동안 유효한 캐시

    # 2. Samba 서버 설치
    - name: Install Samba server
      apt:
        name: samba
        state: present

    # 3. 공유 디렉토리 생성
    - name: Create shared directory
      file:
        path: /humans
        state: directory
        mode: '0777'  # 모든 사용자에게 읽기, 쓰기, 실행 권한 부여

    # 4. Samba 설정 파일 수정 (/etc/samba/smb.conf)
    - name: Configure smb.conf for Samba shares
      blockinfile:
        path: /etc/samba/smb.conf
        marker: "# {ansible_managed} #"
        block: |
          [humans]
          path = /humans
          browseable = yes
          read only = no
          guest ok = yes
          create mask = 0777
          directory mask = 0777

    # 5. Samba 사용자 추가 (기본 사용자는 guest)
    - name: Add Samba user (smbuser)
      user:
        name: user1
        password: "{{ '123456' | password_hash('sha512') }}"
        state: present

    # 6. Samba 사용자 비밀번호 설정
    - name: Set Samba password for smbuser
      command: echo -e "123456\n123456" | smbpasswd -a -s user1
      args:
        creates: /etc/samba/smbpasswd

    # 7. Samba 서비스 시작
    - name: Ensure Samba service is running
      service:
        name: smbd
        state: restarted
        enabled: yes  # 부팅 시 자동 시작

